### ISSUE TITLE
No module urlparse

### ISSUE THREAD

**Issue by Decker-Mage** [harmtemolder/calibre-store-the-eye#1]
calibre, version 5.2.0
ERROR: Unhandled exception: <b>ModuleNotFoundError</b>:No module named 'urlparse'

calibre 5.2  embedded-python: True is64bit: False
Windows-10-10.0.18362-SP0 Windows ('32bit', 'WindowsPE')
32bit process running on 64bit windows
('Windows', '10', '10.0.18362')
Python 3.8.5
Windows: ('10', '10.0.18362', 'SP0', 'Multiprocessor Free')
Interface language: None
Successfully initialized third party plugins: Find Duplicates (1, 8, 0)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 317, in add_plugin
  File "calibre\customize\ui.py", line 472, in add_plugin
  File "calibre\customize\ui.py", line 61, in load_plugin
  File "calibre\customize\zipplugin.py", line 282, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre\customize\zipplugin.py", line 181, in exec_module
  File "calibre_plugins.dummy1.__init__", line 8, in <module>
ModuleNotFoundError: No module named 'urlparse'

**Comment by patredtheknight** [comment]
Same issue on linux:

calibre 5.2  embedded-python: True is64bit: True
Linux-5.4.0-48-generic-x86_64-with-glibc2.2.5 Linux ('64bit', 'ELF')
('Linux', '5.4.0-48-generic', '#52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020')
Python 3.8.5
Interface language: None
Successfully initialized third party plugins:  [...]
Traceback (most recent call last):
  File "calibre/gui2/preferences/plugins.py", line 317, in add_plugin
  File "calibre/customize/ui.py", line 472, in add_plugin
  File "calibre/customize/ui.py", line 61, in load_plugin
  File "calibre/customize/zipplugin.py", line 282, in load
  File "importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "calibre/customize/zipplugin.py", line 181, in exec_module
  File "calibre_plugins.dummy2.__init__", line 8, in <module>
    import urlparse
ModuleNotFoundError: No module named 'urlparse'

**Comment by harmtemolder** [comment]
Ah, that might have something to do with calibre switching from python2 to python3. @Decker-Mage or @patredtheknight, does one of you feel like upgrading this plugin to python3? (I won't have time to do it myself in the coming weeks.)

**Comment by harmtemolder** [comment]
Updated the plugin to Python 3: https://github.com/harmtemolder/calibre-store-the-eye/releases/tag/v0.2.0-alpha
